global:
  scrape_interval: 15s
  scrape_timeout: 10s
  
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets:
          - localhost:9000
  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: [app:80]

  - job_name: 'mysql'
    metrics_path: /metrics
    static_configs:
      - targets: [database:3306]

