apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuro-app
  namespace: neuro-space
  labels:
    app: neuro-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuro-app
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Deploy $(date)"
      labels:
        app: neuro-app
    spec:
      containers:
        - name: neuro-app
          image: spomega/neuronation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: neuro-secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neuro-secrets
                  key: db_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: neuro-secrets
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: neuro-secrets
                  key: db_database

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
