apiVersion: v1
kind: Service
metadata:
  name: neuro-app
  namespace: neuro-space
  labels:
    app: neuro-app
spec:
  selector:
    app: neuro-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP