name: Build and deploy
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
env:
  DOCKER_HUB_APP_REPOSITORY: spomega
  EKS_CLUSTER_NAME: sage-uat
  AWS_REGION: eu-central-1
  EKS_NAMESPACE: neuro-space

jobs:
  build-and-upload-docker-image:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: QEMU Setup
        uses: docker/setup-qemu-action@v2
      -
        name: Buildx Docker Setup
        uses: docker/setup-buildx-action@v2
      -
        name: DockerHub and Push Image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build And Push Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: spomega/neuronation:latest