name: Linting and Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.composer-cache.outputs.cache-hit }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, mysql, sqlite, zip

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

  cs-fix:
    name: PHP Code Style Fixer
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Set up PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.3'
      #     extensions: mbstring, pdo, mysql, zip

      # - name: Install Composer Dependencies
      #   run: |
      #     composer install --no-interaction --prefer-dist --optimize-autoloader

      # Run PHP-CS-Fixer
      - name: Run PHP-CS-Fixer
        run: |
          vendor/bin/php-cs-fixer fix --dry-run --verbose --diff --using-cache=no
        continue-on-error: true

      - name: Show diff (if any)
        if: failure()
        run: git diff

  tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    needs: setup
    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Set up PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.3'
      #     extensions: mbstring, pdo, sqlite, mysql

      # - name: Install Composer Dependencies
      #   run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Set up environment
      - name: Copy .env
        run: cp .env.example .env

      # Generate Laravel application key
      - name: Generate App Key
        run: php artisan key:generate

      # Run database migrations (for testing purposes)
      - name: Run Migrations
        run: php artisan migrate --env=testing --force

      # Run PHPUnit
      - name: Run Tests
        run: php artisan test --coverage-text

      # Optional: Run Static Analysis (e.g., for Laravel Pint)
      # - name: Run Laravel Pint (optional static analysis)
      #   run: vendor/bin/pint --test
