name: Linting and Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cs-fix:
    name: PHP Code Style Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, mysql, zip

      - name: Install Composer Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHP-CS-Fixer
        run: |
          vendor/bin/php-cs-fixer fix --dry-run --verbose --diff --using-cache=no
        continue-on-error: true

      - name: Show diff (if any)
        if: failure()
        run: git diff

  tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    needs: cs-fix
    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, sqlite, mysql

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --env=testing --force

      - name: Run Tests
        run: php artisan test --coverage-text

